# Generated by Django 5.1.4 on 2025-01-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messagereadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
    ]
