# Generated by Django 5.1.4 on 2025-01-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_messagereadstatus_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
