# Generated by Django 5.1.4 on 2025-01-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_messagereadstatus_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagereadstatus',
            options={'ordering': ['-read_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
